import { useCallback, useEffect, useRef, useState } from 'react';
import type { FormatId, InterviewRole } from '../../data/interviewRoles';
import { FORMATS } from '../../data/interviewRoles';
import {
  panelistsFor,
  type AnswerRecord,
  type EngineQuestion,
  type SessionConfig,
} from '../../lib/interviewEngine';
import { engineAnalyze, engineStart, type EngineSource } from '../../lib/api';
import { useSpeechToText } from '../../lib/speech';
import { speak, stopSpeaking, ttsSupported } from '../../lib/tts';

interface Props {
  role: InterviewRole;
  format: FormatId;
  useVideo: boolean;
  resumeSkills: string[];
  resumeProjects: string;
  onFinish: (records: AnswerRecord[]) => void;
  onAbort: () => void;
}

type InputMode = 'typed' | 'voice';

export default function InterviewSession({ role, format, useVideo, resumeSkills, resumeProjects, onFinish, onAbort }: Props) {
  const configRef = useRef<SessionConfig>({ role, format, resumeSkills, resumeProjects });
  const [queue, setQueue] = useState<EngineQuestion[]>([]);
  const [engineSource, setEngineSource] = useState<EngineSource | null>(null);
  const [busy, setBusy] = useState(false);
  const [qIndex, setQIndex] = useState(0);
  const [records, setRecords] = useState<AnswerRecord[]>([]);
  const [mode, setMode] = useState<InputMode>('typed');
  const [typed, setTyped] = useState('');
  const [followUps, setFollowUps] = useState(0);
  const [reaction, setReaction] = useState<string | null>(null);
  const [startedAt, setStartedAt] = useState<number>(() => Date.now());
  /** Interviewer voice-over (browser TTS). Off by default; user opt-in. */
  const [voiceOver, setVoiceOver] = useState(false);
  /** Live seconds spent on the current question. */
  const [questionSec, setQuestionSec] = useState(0);


  const speech = useSpeechToText();
  const question = queue[qIndex];
  const isLast = qIndex >= queue.length - 1;
  const totalPlanned = queue.length;

  // Load initial questions (on-device engine).
  useEffect(() => {
    const count = FORMATS.find((f) => f.id === format)?.questionCount ?? 5;
    const { questions, source } = engineStart(configRef.current, count);
    setQueue(questions);
    setEngineSource(source);
    setStartedAt(Date.now());
  }, [format]);

  // Interviewer voice-over: read each new question aloud when enabled.
  useEffect(() => {
    if (voiceOver && question) speak(question.text);
    return stopSpeaking;
  }, [voiceOver, question]);

  // Per-question timer tick.
  useEffect(() => {
    setQuestionSec(0);
    const id = window.setInterval(() => {
      setQuestionSec(Math.round((Date.now() - startedAt) / 1000));
    }, 1000);
    return () => window.clearInterval(id);
  }, [startedAt]);

  // ── Camera (self-view only; honestly labeled) ──
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const [camError, setCamError] = useState<string | null>(null);
  const [camOn, setCamOn] = useState(false);

  useEffect(() => {
    if (!useVideo) return;
    let cancelled = false;
    navigator.mediaDevices
      ?.getUserMedia({ video: true, audio: false })
      .then((stream) => {
        if (cancelled) { stream.getTracks().forEach((t) => t.stop()); return; }
        streamRef.current = stream;
        setCamOn(true);
        if (videoRef.current) videoRef.current.srcObject = stream;
      })
      .catch(() => setCamError('Camera unavailable or permission denied. Continuing without video — no visual metrics will be shown (we never fake them).'));
    return () => {
      cancelled = true;
      streamRef.current?.getTracks().forEach((t) => t.stop());
    };
  }, [useVideo]);

  useEffect(() => {
    if (camOn && videoRef.current && streamRef.current) videoRef.current.srcObject = streamRef.current;
  }, [camOn, qIndex]);

  const currentAnswer = mode === 'voice' ? speech.transcript : typed;
  const wordCount = currentAnswer.trim() ? currentAnswer.trim().split(/\s+/).length : 0;

  const advance = useCallback(
    (record: AnswerRecord, followUp: EngineQuestion | null) => {
      const newRecords = [...records, record];
      setRecords(newRecords);

      // brief interviewer reaction based on honest measured average
      const measured = Object.values(record.scores).filter((v): v is number => v !== null);
      const avg = measured.length ? measured.reduce((a, b) => a + b, 0) / measured.length : 0;
      if (record.mode === 'skipped') setReaction('The interviewer notes your silence and moves on.');
      else if (avg >= 75) setReaction(format === 'stress' ? '“Hmph. Adequate.”' : '“Good answer — I like the specifics.”');
      else if (avg >= 45) setReaction('“Okay… let\u2019s continue.”');
      else setReaction(format === 'stress' ? '“That was weak, and you know it.”' : '“I was hoping for more detail there.”');

      // adaptive follow-up injection (generated by the active engine)
      let nextQueue = queue;
      if (followUp) {
        nextQueue = [...queue.slice(0, qIndex + 1), followUp, ...queue.slice(qIndex + 1)];
        setQueue(nextQueue);
        setFollowUps((n) => n + 1);
      }

      if (qIndex + 1 >= nextQueue.length) {
        speech.stop();
        onFinish(newRecords);
        return;
      }

      // reset for next question
      setQIndex((i) => i + 1);
      setTyped('');

      speech.stop();
      speech.reset();
      setStartedAt(Date.now());
      window.setTimeout(() => setReaction(null), 3500);
    },
    [records, queue, qIndex, speech, onFinish, format],
  );

  const submit = async () => {
    if (busy) return;
    setBusy(true);
    const durationSec = mode === 'voice' && speech.elapsedSec > 0 ? speech.elapsedSec : Math.round((Date.now() - startedAt) / 1000);
    const answerMode: 'typed' | 'voice' | 'skipped' = currentAnswer.trim() === '' ? 'skipped' : mode;
    const { record, followUp, source } = await engineAnalyze(
      configRef.current, question, currentAnswer, answerMode, durationSec, followUps,
    );
    setEngineSource(source);
    advance(record, followUp);
    setBusy(false);
  };

  const skip = async () => {
    if (busy) return;
    setBusy(true);
    const { record, followUp, source } = await engineAnalyze(
      configRef.current, question, '', 'skipped', 0, followUps,
    );
    setEngineSource(source);
    advance(record, followUp);
    setBusy(false);
  };

  const switchMode = (m: InputMode) => {
    if (m === mode) return;
    if (m === 'voice' && !speech.supported) return;
    setMode(m);
    if (m === 'typed') speech.stop();
  };

  const panel = panelistsFor(format);
  const formatMeta = FORMATS.find((f) => f.id === format);

  if (!question) {
    return (
      <div className="flex min-h-[50vh] flex-col items-center justify-center gap-4" role="status">
        <div className="h-10 w-10 animate-spin rounded-full border-4" style={{ borderColor: 'var(--border)', borderTopColor: 'var(--primary)' }} />
        <p className="text-sm font-semibold" style={{ color: 'var(--muted)' }}>Preparing your {role.title} questions…</p>
      </div>
    );
  }

  return (
    <div>
      {/* Header */}
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
        <div>
          <div className="text-sm font-semibold uppercase tracking-wider text-indigo-500">{formatMeta?.icon} {formatMeta?.name}</div>
          <h1 className="text-2xl font-extrabold text-slate-900">{role.title} Interview</h1>
        </div>
        <div className="flex items-center gap-3">
          {engineSource && (
            <span className="badge badge-blue">
              {engineSource === 'ai-gemini' ? '🤖 AI Analysis' : '📊 Rule-Based Scoring'}
            </span>
          )}
          <span className="rounded-full bg-slate-900 px-4 py-1.5 text-xs font-bold text-white" aria-live="polite">
            Question {qIndex + 1} / {totalPlanned}
          </span>
          <button
            onClick={() => { speech.stop(); onAbort(); }}
            className="rounded-full border border-rose-200 px-4 py-1.5 text-xs font-bold text-rose-600 transition hover:bg-rose-50 focus:outline-none focus-visible:ring-4 focus-visible:ring-rose-200"
          >
            End Interview
          </button>
        </div>
      </div>

      <div className="mb-4 h-1.5 overflow-hidden rounded-full bg-slate-200" role="progressbar" aria-valuenow={qIndex + 1} aria-valuemin={0} aria-valuemax={totalPlanned} aria-label="Interview progress">
        <div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-indigo-600 transition-all duration-500" style={{ width: `${((qIndex + 1) / totalPlanned) * 100}%` }} />
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Left: interviewer(s) + question */}
        <div className="space-y-4 lg:col-span-2">
          {/* Panel strip */}
          {panel.length > 1 && (
            <div className="flex gap-2" aria-label="Interview panel">
              {panel.map((p) => (
                <div
                  key={p.name}
                  className={`flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-semibold transition ${
                    question.interviewer.name === p.name ? 'border-indigo-400 bg-indigo-50 text-indigo-800' : 'border-slate-200 bg-white text-slate-400'
                  }`}
                >
                  <span aria-hidden="true">{p.avatar}</span> {p.name} · {p.title}
                  {question.interviewer.name === p.name && <span className="ml-1 h-2 w-2 animate-pulse rounded-full bg-emerald-500" aria-label="currently speaking" />}
                </div>
              ))}
            </div>
          )}

          {/* GD peers */}
          {question.peers && (
            <div className="space-y-2" aria-label="Other participants' statements">
              {question.peers.map((peer) => (
                <div key={peer.name + peer.statement} className="flex items-start gap-3 rounded-2xl border border-slate-200 bg-white p-3 text-sm">
                  <span className="text-xl" aria-hidden="true">{peer.avatar}</span>
                  <div>
                    <span className="font-bold text-slate-700">{peer.name}:</span>{' '}
                    <span className="text-slate-600">{peer.statement}</span>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Question card */}
          <div className={`rounded-3xl border-2 p-6 shadow-sm ${format === 'stress' ? 'border-rose-200 bg-rose-50/60' : 'border-indigo-100 bg-white'}`}>
            <div className="flex items-center gap-3">
              <span className="flex h-12 w-12 items-center justify-center rounded-full bg-slate-100 text-2xl" aria-hidden="true">{question.interviewer.avatar}</span>
              <div>
                <div className="font-bold text-slate-900">{question.interviewer.name}</div>
                <div className="text-xs text-slate-400">{question.interviewer.title}</div>
              </div>
              <div className="ml-auto flex items-center gap-2">
                {question.isFollowUp && (
                  <span className="rounded-full bg-violet-100 px-3 py-1 text-[11px] font-bold text-violet-700">⚡ Adaptive follow-up</span>
                )}
                {ttsSupported() && (
                  <button
                    onClick={() => setVoiceOver((v) => !v)}
                    aria-pressed={voiceOver}
                    aria-label={voiceOver ? 'Mute interviewer voice' : 'Have the interviewer read questions aloud'}
                    title={voiceOver ? 'Mute interviewer voice' : 'Read questions aloud'}
                    className={`rounded-full px-3 py-1.5 text-sm transition focus:outline-none focus-visible:ring-4 focus-visible:ring-indigo-200 ${
                      voiceOver ? 'bg-indigo-600 text-white' : 'bg-slate-100 text-slate-500 hover:bg-slate-200'
                    }`}
                  >
                    {voiceOver ? '🔊' : '🔇'}
                  </button>
                )}
              </div>
            </div>
            <p className="mt-4 whitespace-pre-line text-lg font-semibold leading-relaxed text-slate-800" aria-live="polite">
              {question.text}
            </p>
            {question.expectsCode && (
              <p className="mt-2 text-xs font-bold text-indigo-500">💻 Explain your approach, then include pseudo-code in your answer.</p>
            )}
          </div>

          {reaction && (
            <p className="text-sm font-medium italic text-slate-500" aria-live="polite">💭 {reaction}</p>
          )}

          {/* Answer input */}
          <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
            <div className="flex flex-wrap items-center gap-2" role="tablist" aria-label="Answer mode">
              <button
                role="tab"
                aria-selected={mode === 'typed'}
                onClick={() => switchMode('typed')}
                className={`rounded-full px-4 py-2 text-sm font-bold transition focus:outline-none focus-visible:ring-4 focus-visible:ring-indigo-200 ${mode === 'typed' ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}
              >
                ⌨️ Type
              </button>
              <button
                role="tab"
                aria-selected={mode === 'voice'}
                onClick={() => switchMode('voice')}
                disabled={!speech.supported}
                className={`rounded-full px-4 py-2 text-sm font-bold transition focus:outline-none focus-visible:ring-4 focus-visible:ring-indigo-200 ${mode === 'voice' ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'} disabled:cursor-not-allowed disabled:opacity-40`}
              >
                🎙️ Speak
              </button>
              {!speech.supported && (
                <span className="text-xs text-slate-400">Speech-to-text not supported in this browser — typing only. Delivery will honestly show “Not measured”.</span>
              )}
              <span className="ml-auto text-xs font-semibold text-slate-400" aria-live="polite">{wordCount} words</span>
            </div>

            {mode === 'typed' ? (
              <textarea
                rows={question.expectsCode ? 10 : 6}
                value={typed}
                onChange={(e) => setTyped(e.target.value)}
                placeholder={question.expectsCode ? 'Explain your approach…\n\npseudo-code:\nfunction solve(input) {\n  …\n}' : 'Type your answer here. Aim for a structured, specific response…'}
                aria-label="Your answer"
                className={`mt-4 w-full rounded-2xl border border-slate-300 px-4 py-3 text-sm outline-none transition focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100 ${question.expectsCode ? 'font-mono' : ''}`}
              />
            ) : (
              <div className="mt-4">
                <div className="flex items-center gap-3">
                  <button
                    onClick={() => (speech.listening ? speech.stop() : speech.start())}
                    aria-pressed={speech.listening}
                    className={`flex items-center gap-2 rounded-full px-6 py-3 font-bold text-white transition focus:outline-none focus-visible:ring-4 focus-visible:ring-rose-200 ${
                      speech.listening ? 'bg-rose-600 hover:bg-rose-700' : 'bg-indigo-600 hover:bg-indigo-700'
                    }`}
                  >
                    {speech.listening ? (
                      <><span className="relative flex h-3 w-3"><span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-white opacity-75" /><span className="relative inline-flex h-3 w-3 rounded-full bg-white" /></span> Stop Recording</>
                    ) : (
                      <>🎙️ Start Speaking</>
                    )}
                  </button>
                  {speech.listening && <span className="text-sm font-bold text-rose-600" aria-live="polite">● REC {speech.elapsedSec}s</span>}
                </div>
                {speech.error && (
                  <p role="alert" className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs font-medium text-amber-800">⚠️ {speech.error}</p>
                )}
                <div
                  className="mt-4 min-h-24 rounded-2xl border border-dashed border-slate-300 bg-slate-50 px-4 py-3 text-sm text-slate-700"
                  aria-live="polite"
                  aria-label="Live transcript"
                >
                  {speech.transcript || speech.interim ? (
                    <>
                      {speech.transcript}
                      <span className="text-slate-400">{speech.interim ? ` ${speech.interim}` : ''}</span>
                    </>
                  ) : (
                    <span className="text-slate-400">Your live transcript appears here as you speak…</span>
                  )}
                </div>
              </div>
            )}

            <div className="mt-4 flex items-center justify-between">
              <button
                onClick={() => void skip()}
                disabled={busy}
                className="rounded-full px-4 py-2 text-sm font-semibold text-slate-400 transition enabled:hover:text-slate-600 disabled:opacity-40 focus:outline-none focus-visible:ring-4 focus-visible:ring-slate-200"
              >
                Skip (scores 0 — honestly)
              </button>
              <button
                onClick={() => void submit()}
                disabled={currentAnswer.trim() === '' || busy}
                className="rounded-full bg-indigo-600 px-8 py-3 font-semibold text-white shadow-lg shadow-indigo-200 transition enabled:hover:scale-105 enabled:hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-40 focus:outline-none focus-visible:ring-4 focus-visible:ring-indigo-300"
              >
                {busy ? '⏳ Analyzing…' : isLast && followUps >= 2 ? 'Submit & Finish' : 'Submit Answer →'}
              </button>
            </div>


          </div>
        </div>

        {/* Right: video + live honest metrics */}
        <aside className="space-y-4">
          {useVideo && (
            <div className="overflow-hidden rounded-3xl border border-slate-200 bg-slate-900 shadow-sm">
              {camOn ? (
                <video ref={videoRef} autoPlay muted playsInline className="aspect-video w-full object-cover" aria-label="Your camera self-view" />
              ) : (
                <div className="flex aspect-video items-center justify-center p-4 text-center text-xs text-slate-400">
                  {camError ?? 'Requesting camera…'}
                </div>
              )}
              <p className="bg-slate-800 px-3 py-2 text-[11px] text-slate-400">
                🎥 Self-view only — body language is <span className="font-bold text-slate-300">not auto-scored</span> and nothing is recorded.
              </p>
            </div>
          )}

          <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
            <h3 className="text-sm font-bold text-slate-900">📊 Live metrics (measured only)</h3>
            <dl className="mt-3 space-y-2.5 text-sm">
              <Metric label="Time on question" value={`${Math.floor(questionSec / 60)}:${String(questionSec % 60).padStart(2, '0')}`} />
              <Metric label="Answer length" value={`${wordCount} words`} />
              <Metric
                label="Speaking time"
                value={mode === 'voice' ? `${speech.elapsedSec}s` : '— (typing)'}
              />
              <Metric
                label="Pace (WPM)"
                value={
                  mode === 'voice' && speech.elapsedSec >= 5 && wordCount > 0
                    ? `${Math.round((wordCount / speech.elapsedSec) * 60)}`
                    : 'Not measured'
                }
              />
              <Metric
                label="Mic status"
                value={mode === 'voice' ? (speech.listening ? '🟢 Live' : '⚪ Off') : '⚪ Off — delivery won\u2019t be scored'}
              />
            </dl>
            <p className="mt-3 border-t border-slate-100 pt-3 text-[11px] leading-relaxed text-slate-400">
              🛡️ <span className="font-bold text-slate-500">Honest analytics promise:</span> when your mic or camera is off,
              related metrics show “Not measured” — we never display fabricated scores.
            </p>
          </div>

          <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
            <h3 className="text-sm font-bold text-slate-900">💡 Format tip</h3>
            <p className="mt-2 text-xs leading-relaxed text-slate-500">
              {format === 'stress' && 'Stress interviews test composure, not knowledge. Stay calm, never get defensive, and answer the substance beneath the provocation.'}
              {format === 'gd' && 'In group discussions, quality beats quantity. Reference others\u2019 points by name, add new evidence, and help the group converge.'}
              {format === 'upsc' && 'The board assesses personality, not facts. Be honest, balanced, and grounded — it\u2019s fine to say "I don\u2019t know, but here\u2019s how I\u2019d find out."'}
              {format === 'panel' && 'Address the panelist who asked, but make eye contact with everyone. Tailor depth: technical detail for the expert, outcomes for the director.'}
              {format === 'coding' && 'Think aloud: clarify constraints → propose brute force → optimize → state complexity → then write pseudo-code.'}
              {format === 'behavioural' && 'Use STAR: one concrete Situation, your specific Task, the Actions *you* took, and a measurable Result.'}
            </p>
          </div>
        </aside>
      </div>
    </div>
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between">
      <dt className="text-slate-500">{label}</dt>
      <dd className="font-bold text-slate-800">{value}</dd>
    </div>
  );
}
