import type { ResumeData, Role } from '../types';

interface Props {
  role: Role;
  resume: ResumeData;
  setResume: (r: ResumeData) => void;
  onNext: () => void;
}

const FIELDS: { key: keyof ResumeData; label: string; placeholder: string; textarea?: boolean }[] = [
  { key: 'name', label: 'Full Name', placeholder: 'Aarav Sharma' },
  { key: 'email', label: 'Email', placeholder: 'aarav@example.com' },
  { key: 'phone', label: 'Phone', placeholder: '+91 98765 43210' },
  { key: 'summary', label: 'Professional Summary', placeholder: 'Motivated developer with 2 years of experience building scalable web apps…', textarea: true },
  { key: 'education', label: 'Education', placeholder: 'B.Tech Computer Science, XYZ University — 2025\nCGPA: 8.5/10', textarea: true },
  { key: 'experience', label: 'Experience / Internships', placeholder: 'Frontend Intern @ TechCorp (Jun–Aug 2024)\n• Built dashboard used by 500+ daily users\n• Reduced page load time by 40%', textarea: true },
  { key: 'skills', label: 'Skills (comma separated)', placeholder: 'React, TypeScript, Node.js, Git, REST APIs, SQL' },
  { key: 'projects', label: 'Key Projects', placeholder: 'Task Manager SPA — React + TypeScript\n• Full CRUD with drag-and-drop\n• 95 Lighthouse performance score', textarea: true },
];

/** Counts fields with meaningful content (>3 chars, not just spaces) */
export function resumeCompleteness(r: ResumeData): number {
  const filled = Object.values(r).filter((v) => v.trim().length > 3).length;
  return Math.round((filled / Object.keys(r).length) * 100);
}

function downloadResume(r: ResumeData, roleTitle: string): void {
  const divider = '═'.repeat(50);
  const lines = [
    divider,
    (r.name || 'YOUR NAME').toUpperCase(),
    divider,
    '',
    `Email: ${r.email || '—'}`,
    `Phone: ${r.phone || '—'}`,
    `Target Role: ${roleTitle}`,
    '',
    '── PROFESSIONAL SUMMARY ' + '─'.repeat(28),
    r.summary || '(Not provided)',
    '',
    '── SKILLS ' + '─'.repeat(41),
    r.skills || '(Not provided)',
    '',
    '── EXPERIENCE ' + '─'.repeat(37),
    r.experience || '(Not provided)',
    '',
    '── PROJECTS ' + '─'.repeat(39),
    r.projects || '(Not provided)',
    '',
    '── EDUCATION ' + '─'.repeat(38),
    r.education || '(Not provided)',
    '',
    divider,
    `Generated by CareerPath AI — ${new Date().toLocaleDateString()}`,
  ];
  const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${(r.name || 'resume').replace(/\s+/g, '-')}-Resume.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default function ResumeBuilder({ role, resume, setResume, onNext }: Props) {
  const pct = resumeCompleteness(resume);

  // Smart tips based on actual resume content
  const tips: string[] = [];
  if (!resume.name.trim()) tips.push('Add your full name — it is the first thing recruiters see.');
  if (!resume.email.trim()) tips.push('Add your email address for contact.');
  if (resume.summary.trim().length > 0 && resume.summary.trim().length < 60) tips.push('Your summary is too short. Expand to 2–3 sentences highlighting your value proposition.');
  if (resume.summary.trim().length === 0) tips.push('Add a professional summary — a 2–3 sentence elevator pitch about your background.');
  if (resume.skills.trim().length > 0 && !resume.skills.toLowerCase().includes(role.skills[0]?.name.split(' ')[0].toLowerCase())) {
    tips.push(`Add "${role.skills[0]?.name}" to your skills — it is critical for ${role.title} applications.`);
  }
  if (!resume.experience.trim()) tips.push('No experience listed. Add internships, freelance work, or list your roadmap projects as hands-on experience.');
  if (resume.experience.trim().length > 0 && !/\d/.test(resume.experience)) tips.push('Quantify your experience: "increased revenue by 20%", "served 500+ users".');
  if (!resume.projects.trim()) tips.push('Add at least 1–2 portfolio projects with measurable outcomes.');
  if (resume.projects.trim().length > 0 && !/\d/.test(resume.projects)) tips.push('Add numbers to your projects: "reduced load time by 40%", "95 Lighthouse score".');
  if (!resume.education.trim()) tips.push('Add your education — degree, institution, and year.');

  return (
    <div className="fade-in">
      <div className="mb-8">
        <div className="text-sm font-semibold uppercase tracking-wider" style={{ color: 'var(--primary)' }}>Step 4 · Resume Builder</div>
        <h1 className="mt-1 text-3xl font-extrabold" style={{ color: 'var(--text)' }}>Build your {role.title} resume</h1>
        <p className="mt-2 text-sm" style={{ color: 'var(--muted)' }}>Fill in each section. Tips update in real-time based on your content.</p>
      </div>

      <div className="grid gap-8 lg:grid-cols-2">
        {/* Form */}
        <div className="space-y-4">
          {/* Completeness bar */}
          <div className="card p-4">
            <div className="flex items-center justify-between text-sm font-semibold">
              <span style={{ color: 'var(--text)' }}>Completeness</span>
              <span style={{ color: pct === 100 ? 'var(--success)' : 'var(--primary)' }}>{pct}%</span>
            </div>
            <div className="mt-2 progress-track">
              <div className="progress-fill" style={{ width: `${pct}%` }} />
            </div>
          </div>

          {FIELDS.map((f) => (
            <label key={f.key} className="block">
              <span className="mb-1 block text-sm font-semibold" style={{ color: 'var(--text)' }}>{f.label}</span>
              {f.textarea ? (
                <textarea
                  rows={3}
                  value={resume[f.key]}
                  onChange={(e) => setResume({ ...resume, [f.key]: e.target.value })}
                  placeholder={f.placeholder}
                  className="input w-full"
                />
              ) : (
                <input
                  value={resume[f.key]}
                  onChange={(e) => setResume({ ...resume, [f.key]: e.target.value })}
                  placeholder={f.placeholder}
                  className="input w-full"
                />
              )}
            </label>
          ))}

          {/* Tips */}
          {tips.length > 0 && (
            <div className="card p-4" style={{ borderColor: 'var(--warning)' }}>
              <h4 className="text-sm font-bold" style={{ color: 'var(--warning)' }}>💡 Resume Tips ({tips.length})</h4>
              <ul className="mt-2 space-y-1.5 text-xs" style={{ color: 'var(--text)' }}>
                {tips.map((t) => (
                  <li key={t} className="flex gap-2"><span style={{ color: 'var(--warning)' }}>→</span>{t}</li>
                ))}
              </ul>
            </div>
          )}
          {tips.length === 0 && pct === 100 && (
            <div className="card p-4" style={{ borderColor: 'var(--success)' }}>
              <span className="text-sm font-bold" style={{ color: 'var(--success)' }}>✅ Your resume looks complete! Review the preview and continue.</span>
            </div>
          )}
        </div>

        {/* Live Preview */}
        <div className="lg:sticky lg:top-6 lg:self-start" id="resume-preview">
          <div className="card overflow-hidden shadow-lg print:shadow-none">
            <div className="px-8 py-6 text-white" style={{ background: 'var(--primary)' }}>
              <h2 className="text-2xl font-extrabold">{resume.name || 'Your Name'}</h2>
              <p className="mt-1 text-sm opacity-80">
                {[resume.email, resume.phone].filter(Boolean).join('  ·  ') || 'email · phone'}
              </p>
              <span className="mt-2 inline-block rounded-full bg-white/20 px-3 py-1 text-xs font-bold">
                {role.title}
              </span>
            </div>
            <div className="space-y-4 px-8 py-6">
              <PreviewSection title="Summary" body={resume.summary} empty="Write a professional summary above…" />
              <PreviewSection title="Skills">
                <div className="flex flex-wrap gap-1.5">
                  {(resume.skills || 'Your skills').split(',').map((s, i) => (
                    <span key={i} className="badge badge-blue">{s.trim()}</span>
                  ))}
                </div>
              </PreviewSection>
              <PreviewSection title="Experience" body={resume.experience} empty="Add your experience above…" />
              <PreviewSection title="Projects" body={resume.projects} empty="Add your projects above…" />
              <PreviewSection title="Education" body={resume.education} empty="Add your education above…" />
            </div>
          </div>
        </div>
      </div>

      <div className="mt-8 flex flex-wrap items-center justify-between gap-3">
        <div className="flex gap-2">
          <button onClick={() => downloadResume(resume, role.title)} className="btn btn-ghost text-sm">
            ⬇️ Download .txt
          </button>
          <button onClick={() => window.print()} className="btn btn-ghost text-sm">
            🖨️ Print / PDF
          </button>
        </div>
        <button onClick={onNext} className="btn btn-primary px-8 py-3">
          Continue to Interview →
        </button>
      </div>
    </div>
  );
}

function PreviewSection({ title, body, empty, children }: { title: string; body?: string; empty?: string; children?: React.ReactNode }) {
  return (
    <div>
      <h3 className="mb-1.5 pb-1 text-xs font-extrabold uppercase tracking-widest" style={{ color: 'var(--muted)', borderBottom: '1px solid var(--border)' }}>{title}</h3>
      {children ?? (
        <p className="whitespace-pre-line text-sm leading-relaxed" style={{ color: body?.trim() ? 'var(--text)' : 'var(--muted)' }}>
          {body?.trim() || empty || '—'}
        </p>
      )}
    </div>
  );
}
